[project]
name = "mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "anthropic>=0.58.2",
    "nest-asyncio>=1.6.0",
    "python-dotenv>=1.1.1",
]
